const cron = require('node-cron');
const Doubt = require('../models/Doubt');
const User = require('../models/User');
const Notification = require('../models/Notification');
const { generateAIAnswer } = require('./aiAnswer');

// Runs every minute, checks for unanswered doubts older than 10 mins
const startAutoAnswerJob = () => {
  cron.schedule('* * * * *', async () => {
    try {
      const tenMinutesAgo = new Date(Date.now() - 15 * 1000);

      // Find doubts that:
      // 1. Are still open
      // 2. Have zero answers
      // 3. Were created more than 10 minutes ago
      // 4. Haven't been AI answered yet
      const unansweredDoubts = await Doubt.find({
        status: 'open',
        answerCount: 0,
        createdAt: { $lte: tenMinutesAgo },
        aiAnswered: { $ne: true }
      }).populate('author', 'name email');

      if (unansweredDoubts.length === 0) return;

      console.log(`🤖 Found ${unansweredDoubts.length} unanswered doubt(s). Generating AI answers...`);

      for (const doubt of unansweredDoubts) {
        try {
          // Generate AI answer
          const aiContent = await generateAIAnswer(doubt);

          // Find or create AI bot user
          let aiUser = await User.findOne({ email: 'ai@smartdoubt.com' });
          if (!aiUser) {
            aiUser = await User.create({
              name: 'SmartDoubt AI',
              email: 'ai@smartdoubt.com',
              password: 'AIBot@SmartDoubt2025',
              isVerified: true,
              role: 'admin',
              avatar: '🤖'
            });
          }

          // Add AI answer to doubt
          doubt.answers.push({
            content: `🤖 **AI Generated Answer**\n\n${aiContent}\n\n---\n*This answer was automatically generated by SmartDoubt AI because no peer answered within 10 minutes. A human answer may still arrive and could be more accurate.*`,
            author: aiUser._id,
            isAnonymous: false,
            upvoteCount: 0
          });

          // Mark as AI answered so we don't answer again
          doubt.aiAnswered = true;
          doubt.answerCount = doubt.answers.length;
          await doubt.save();

          // Notify the doubt author
          await Notification.create({
            recipient: doubt.author._id,
            type: 'new_answer',
            message: `🤖 SmartDoubt AI answered your doubt "${doubt.title.substring(0, 50)}..." since no peer answered within 10 minutes.`,
            relatedDoubt: doubt._id
          });

          console.log(`✅ AI answered doubt: "${doubt.title}"`);

        } catch (err) {
          console.error(`❌ Failed to AI answer doubt ${doubt._id}:`, err.message);
        }
      }

    } catch (error) {
      console.error('❌ Auto answer job error:', error.message);
    }
  });

  console.log('🤖 AI Auto-Answer job started — checks every minute');
};

module.exports = { startAutoAnswerJob };